export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TENANT_SCOPE_MISMATCH: 'TENANT_SCOPE_MISMATCH',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  POLICY_DENIED: 'POLICY_DENIED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  CONNECTOR_UNAVAILABLE: 'CONNECTOR_UNAVAILABLE',
  PAYMENT_RECONCILIATION_FAILED: 'PAYMENT_RECONCILIATION_FAILED',
  DEVICE_QUARANTINED: 'DEVICE_QUARANTINED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RUN_STATE_INVALID: 'RUN_STATE_INVALID',
  PAYMENT_PROVIDER_DEGRADED: 'PAYMENT_PROVIDER_DEGRADED',
  APPROVAL_ALREADY_DECIDED: 'APPROVAL_ALREADY_DECIDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
    public details?: Record<string, unknown>,
    public httpStatus: number = 400,
  ) {
    super(message);
    this.name = 'AppError';
  }
}
